import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        {/*<div className="grid min-w-svw min-h-dvh grid-cols-[2.5rem_repeat(6,minmax(0,1fr))_2.5rem] lg:grid-cols-[2.5rem_repeat(12,minmax(0,1fr))_2.5rem] gap-4">*/}
        {children}
        {/*</div>*/}
      </body>
    </html>
  );
}
